-- Diagnostico ORA-01438 : colunas NUMBER(p,s) pequenas demais.
-- Uma passagem por variante. Devolve as colunas cuja parte INTEIRA real
-- nao cabe em (p - s) digitos. Coluna vazia = variante sem problema.
SET LINESIZE 32000
COLUMN colunas_que_estouram FORMAT A150

  SELECT 1 AS ins,
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_LGD_PREDICTIF_LOCAL,0)))))) > 4
              THEN 'P1_18_1(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_TRC,0)))))) > 4
              THEN 'P1_18_10(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN NVL((C_ENR.MNT_EAD_TOT), 0) <0 THEN 0 ELSE NVL((C_ENR.MNT_EAD_TOT), 0)END,0)))))) > 16
              THEN 'P1_18_5(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_RISQUE), 0),0)))))) > 16
              THEN 'P1_4_9(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when (C_ENR.CD_TYPE_RISQUE LIKE 'TRE5%' OR C_ENR.CD_TYPE_RISQUE LIKE 'TRE4%') THEN CASE WHEN NVL((C_ENR.MNT_SOLD_K_A), 0) <0 THEN 0 ELSE NVL((C_ENR.MNT_SOLD_K_A), 0)END ELSE NULL END,0)))))) > 16
              THEN 'P1_4_6(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN C_ENR.MNT_VTR IS null THEN NULL ELSE NVL((C_ENR.MNT_VTR), 0) END,0)))))) > 16
              THEN 'P1_4_21(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when C_ENR.CD_TYPE_RISQUE = 'TRE502' then NVL((C_ENR.MNT_VTR), 0) else NULL END,0)))))) > 16
              THEN 'P1_3_40(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when C_ENR.CD_TYPE_RISQUE = 'TRE502' then NVL((C_ENR.MNT_HYPOTHEQUE), 0) else NULL END,0)))))) > 16
              THEN 'P1_3_42(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when NVL(C_ENR.MNT_VR, 0) >= 0 then NVL((C_ENR.MNT_VR), 0) else 0 END,0)))))) > 16
              THEN 'P1_5_19(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Substr(NVL(C_ENR.MATURITE_EFF, 0) ,4,6),0)))))) > 2
              THEN 'P1_3_20(6,4) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_CONTRAT_ORIGINE,0)))))) > 16
              THEN 'P1_22_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_INT_EFF_ORI,0)))))) > 4
              THEN 'P1_22_13(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_CLT_OCT,0)))))) > 4
              THEN 'P1_22_19(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_PLAFOND,0)))))) > 4
              THEN 'P1_22_23(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_PLANCHER,0)))))) > 4
              THEN 'P1_22_24(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.PRD_REV_TAUX_NBR), 0),0)))))) > 3
              THEN 'P1_22_26(3,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_CLT_PRD_EN_CRS,0)))))) > 4
              THEN 'P1_22_27(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_MRG_ADD,0)))))) > 4
              THEN 'P1_22_28(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_MRG_MULT,0)))))) > 4
              THEN 'P1_22_29(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_PREM_DBLQ_FONDS is null then NULL else C_ENR.MNT_PREM_DBLQ_FONDS end,0)))))) > 16
              THEN 'P1_22_32(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN C_ENR.CAP_THEO_REST<0 THEN 0 ELSE C_ENR.CAP_THEO_REST END,0)))))) > 16
              THEN 'P1_22_34(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_ACQUISITION), 0),0)))))) > 16
              THEN 'P1_22_44(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_ECH_EN_COURS,0)))))) > 16
              THEN 'P1_22_60(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_IDEMNITE_RES,0)))))) > 16
              THEN 'P1_29_1(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.CD_TYPE_RISQUE like 'TRE%' then NVL(CEIL((C_ENR.DT_FIN_ENG - C_ENR.DT_DEBUT_ENG) / 30), 0) else 0 end,0)))))) > 5
              THEN 'P1_31_17(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.CD_TYPE_RISQUE like 'TRE%' then NVL(CEIL((C_ENR.DT_FIN_ENG - C_ENR.DT_DEBUT_ENG) / 30), 0) else 0 end,0)))))) > 5
              THEN 'P1_31_18(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_MRTR is not null then C_ENR.MNT_MRTR else NULL end,0)))))) > 19
              THEN 'P1_21_30(21,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.ETV_RATIO,0)))))) > 15
              THEN 'P1_21_43(24,9) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_DSCR,0)))))) > 4
              THEN 'P1_21_81(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_DSCR_PREC,0)))))) > 4
              THEN 'P1_21_82(9,5) ' END
           AS colunas_que_estouram
    FROM ENG_CORP_P1 C_ENR
   WHERE A_EXTRAIRE = 'O'
      AND (C_ENR.CD_CONSO_CPT = 'TOTAL' OR 'TOTAL' = 'TOTAL')
      AND NVL(C_ENR.CD_ARR_PAIEMENT,'N') = 'N'
      AND NVL(C_ENR.FLAG_HN,'N')         = 'N'
      AND ( NVL(C_ENR.MNT_CRD,0) - NVL(C_ENR.MNT_VR,0) >= 1
            OR NVL(C_ENR.MNT_VR,0) >= 1 )
      AND C_ENR.CD_TYPE_RISQUE NOT IN ('TRE100','SIG201','EQU101','VAR104')
UNION ALL
  SELECT 2 AS ins,
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_LGD_PREDICTIF_LOCAL,0)))))) > 4
              THEN 'P1_18_1(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_TRC,0)))))) > 4
              THEN 'P1_18_10(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN NVL((C_ENR.MNT_EAD_TOT), 0) <0 THEN 0 ELSE NVL((C_ENR.MNT_EAD_TOT), 0)END,0)))))) > 16
              THEN 'P1_18_5(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 16
              THEN 'P1_4_9(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL(C_ENR.MNT_SOLD_K_A, 0),0)))))) > 16
              THEN 'P1_4_14(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when (C_ENR.CD_TYPE_RISQUE LIKE 'TRE5%' OR C_ENR.CD_TYPE_RISQUE LIKE 'TRE4%') THEN CASE WHEN NVL((C_ENR.MNT_SOLD_K_A), 0) <0 THEN 0 ELSE NVL((C_ENR.MNT_SOLD_K_A), 0)END ELSE NULL END,0)))))) > 16
              THEN 'P1_4_6(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN C_ENR.MNT_VTR IS null THEN NULL ELSE NVL((C_ENR.MNT_VTR), 0) END,0)))))) > 16
              THEN 'P1_4_21(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when C_ENR.CD_TYPE_RISQUE = 'TRE502' and C_ENR.CD_USAGE_BIEN_IMM = '2' then 0 else NULL END,0)))))) > 16
              THEN 'P1_3_40(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when C_ENR.CD_TYPE_RISQUE = 'TRE502' and C_ENR.CD_USAGE_BIEN_IMM = '2' then 0 else NULL END,0)))))) > 16
              THEN 'P1_3_42(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when NVL(C_ENR.MNT_VR, 0) >= 0 then NVL((C_ENR.MNT_VR), 0) else 0 END,0)))))) > 16
              THEN 'P1_5_19(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Substr(1 ,4,6),0)))))) > 2
              THEN 'P1_3_20(6,4) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_CONTRAT_ORIGINE,0)))))) > 16
              THEN 'P1_22_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_INT_EFF_ORI,0)))))) > 4
              THEN 'P1_22_13(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_CLT_OCT,0)))))) > 4
              THEN 'P1_22_19(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_PLAFOND,0)))))) > 4
              THEN 'P1_22_23(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_PLANCHER,0)))))) > 4
              THEN 'P1_22_24(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.PRD_REV_TAUX_NBR), 0),0)))))) > 3
              THEN 'P1_22_26(3,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_CLT_PRD_EN_CRS,0)))))) > 4
              THEN 'P1_22_27(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_MRG_ADD,0)))))) > 4
              THEN 'P1_22_28(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_MRG_MULT,0)))))) > 4
              THEN 'P1_22_29(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_PREM_DBLQ_FONDS is null then NULL else C_ENR.MNT_PREM_DBLQ_FONDS end,0)))))) > 16
              THEN 'P1_22_32(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN C_ENR.CAP_THEO_REST <0 THEN 0 ELSE C_ENR.CAP_THEO_REST END,0)))))) > 16
              THEN 'P1_22_34(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_ACQUISITION), 0),0)))))) > 16
              THEN 'P1_22_44(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_ECH_EN_COURS,0)))))) > 16
              THEN 'P1_22_60(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_IDEMNITE_RES,0)))))) > 16
              THEN 'P1_29_1(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.CD_TYPE_RISQUE like 'TRE%' then NVL(CEIL((C_ENR.DT_FIN_ENG - C_ENR.DT_DEBUT_ENG) / 30), 0) else 0 end,0)))))) > 5
              THEN 'P1_31_17(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.CD_TYPE_RISQUE like 'TRE%' then NVL(CEIL((C_ENR.DT_FIN_ENG - C_ENR.DT_DEBUT_ENG) / 30), 0) else 0 end,0)))))) > 5
              THEN 'P1_31_18(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_MRTR is not null then C_ENR.MNT_MRTR else NULL end,0)))))) > 19
              THEN 'P1_21_30(21,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.ETV_RATIO,0)))))) > 15
              THEN 'P1_21_43(24,9) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_DSCR,0)))))) > 4
              THEN 'P1_21_81(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_DSCR_PREC,0)))))) > 4
              THEN 'P1_21_82(9,5) ' END
           AS colunas_que_estouram
    FROM ENG_CORP_P1 C_ENR
   WHERE A_EXTRAIRE = 'O'
      AND (C_ENR.CD_CONSO_CPT = 'TOTAL' OR 'TOTAL' = 'TOTAL')
      AND NVL(C_ENR.CD_ARR_PAIEMENT,'N') = 'Y'
      AND NVL(C_ENR.FLAG_HN,'N')         = 'N'
      AND NVL(C_ENR.MNT_SOLD_K_A,0) >= 1
      AND C_ENR.CD_TYPE_RISQUE NOT IN ('TRE100','SIG201','EQU101','VAR104')
      AND ( C_ENR.CD_TYPE_RISQUE NOT LIKE 'TRE2%' )
UNION ALL
  SELECT 3 AS ins,
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 4
              THEN 'P1_18_1(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 4
              THEN 'P1_18_10(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 16
              THEN 'P1_18_5(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_RISQUE), 0),0)))))) > 16
              THEN 'P1_4_9(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 16
              THEN 'P1_4_6(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN C_ENR.MNT_VTR IS null THEN NULL ELSE 0 END,0)))))) > 16
              THEN 'P1_4_21(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when C_ENR.CD_TYPE_RISQUE = 'TRE502' then NVL((C_ENR.MNT_VTR), 0) else NULL END,0)))))) > 16
              THEN 'P1_3_40(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Case when C_ENR.CD_TYPE_RISQUE = 'TRE502' then NVL((C_ENR.MNT_HYPOTHEQUE), 0) else NULL END,0)))))) > 16
              THEN 'P1_3_42(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 16
              THEN 'P1_5_19(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(Substr(NVL(C_ENR.MATURITE_EFF, 0) ,4,6),0)))))) > 2
              THEN 'P1_3_20(6,4) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_CONTRAT_ORIGINE,0)))))) > 16
              THEN 'P1_22_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_INT_EFF_ORI,0)))))) > 4
              THEN 'P1_22_13(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_CLT_OCT,0)))))) > 4
              THEN 'P1_22_19(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_PLAFOND,0)))))) > 4
              THEN 'P1_22_23(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_PLANCHER,0)))))) > 4
              THEN 'P1_22_24(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.PRD_REV_TAUX_NBR), 0),0)))))) > 3
              THEN 'P1_22_26(3,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_CLT_PRD_EN_CRS,0)))))) > 4
              THEN 'P1_22_27(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_MRG_ADD,0)))))) > 4
              THEN 'P1_22_28(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_MRG_MULT,0)))))) > 4
              THEN 'P1_22_29(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_PREM_DBLQ_FONDS is null then NULL else C_ENR.MNT_PREM_DBLQ_FONDS end,0)))))) > 16
              THEN 'P1_22_32(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN C_ENR.CAP_THEO_REST <0 THEN 0 ELSE C_ENR.CAP_THEO_REST END,0)))))) > 16
              THEN 'P1_22_34(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_ACQUISITION), 0),0)))))) > 16
              THEN 'P1_22_44(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_ECH_EN_COURS,0)))))) > 16
              THEN 'P1_22_60(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_IDEMNITE_RES,0)))))) > 16
              THEN 'P1_29_1(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.CD_TYPE_RISQUE like 'TRE%' then NVL(CEIL((C_ENR.DT_FIN_ENG - C_ENR.DT_DEBUT_ENG) / 30), 0) else 0 end,0)))))) > 5
              THEN 'P1_31_17(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.CD_TYPE_RISQUE like 'TRE%' then NVL(CEIL((C_ENR.DT_FIN_ENG - C_ENR.DT_DEBUT_ENG) / 30), 0) else 0 end,0)))))) > 5
              THEN 'P1_31_18(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_MRTR is not null then C_ENR.MNT_MRTR else NULL end,0)))))) > 19
              THEN 'P1_21_30(21,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.ETV_RATIO,0)))))) > 15
              THEN 'P1_21_43(24,9) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_DSCR,0)))))) > 4
              THEN 'P1_21_81(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_DSCR_PREC,0)))))) > 4
              THEN 'P1_21_82(9,5) ' END
           AS colunas_que_estouram
    FROM ENG_CORP_P1 C_ENR
   WHERE A_EXTRAIRE = 'O'
      AND (C_ENR.CD_CONSO_CPT = 'TOTAL' OR 'TOTAL' = 'TOTAL')
      AND NVL(C_ENR.CD_ARR_PAIEMENT,'N') = 'Y'
      AND NVL(C_ENR.FLAG_HN,'N')         = 'N'
      AND C_ENR.CD_TYPE_RISQUE NOT IN ('TRE100','SIG201','EQU101','VAR104')
      AND ( C_ENR.CD_TYPE_RISQUE NOT LIKE 'TRE2%' )
      AND ( NVL(C_ENR.MNT_CRD,0) - NVL(C_ENR.MNT_VR,0) >= 1
            OR NVL(C_ENR.MNT_VR,0) >= 1 )
UNION ALL
  SELECT 4 AS ins,
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_SOLDE), 0),0)))))) > 16
              THEN 'P1_4_2(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_LOYER,0)))))) > 16
              THEN 'P1_4_14(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(ABS(TRUNC(C_ENR.MATURITE_EFF)),0)))))) > 2
              THEN 'P1_3_20(6,4) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_CONTRAT_ORIGINE,0)))))) > 16
              THEN 'P1_22_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_ACQUISITION), 0),0)))))) > 16
              THEN 'P1_22_44(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 5
              THEN 'P1_31_17(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 5
              THEN 'P1_31_18(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_MRTR is not null then C_ENR.MNT_MRTR else NULL end,0)))))) > 19
              THEN 'P1_21_30(21,2) ' END
           AS colunas_que_estouram
    FROM ENG_CORP_P1 C_ENR
   WHERE A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = 'TOTAL' OR 'TOTAL' = 'TOTAL')
      AND C_ENR.CD_TYPE_RISQUE IN ('TRE100')
UNION ALL
  SELECT 5 AS ins,
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL((CASE WHEN C_ENR.CD_TYPE_RISQUE = 'TRE201' AND NVL(C_ENR.MNT_SOLDE, 0) >=0 THEN NVL((C_ENR.MNT_SOLDE), 0) ELSE NULL END ),0)))))) > 16
              THEN 'P1_4_4(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_CRD), 0),0)))))) > 16
              THEN 'P1_4_9(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_LOYER,0)))))) > 16
              THEN 'P1_4_14(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL((CASE WHEN C_ENR.CD_TYPE_RISQUE <> 'TRE201' THEN NVL((C_ENR.MNT_INT_RD), 0) ELSE NULL END ),0)))))) > 16
              THEN 'P1_4_6(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL(C_ENR.MNT_MTM, 0),0)))))) > 16
              THEN 'P1_3_52(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(ABS(TRUNC(NVL(C_ENR.MATURITE_EFF, 0))),0)))))) > 2
              THEN 'P1_3_20(6,4) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_ELBE,0)))))) > 4
              THEN 'P1_4_30(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_CONTRAT_ORIGINE,0)))))) > 16
              THEN 'P1_22_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_INT_EFF_ORI,0)))))) > 4
              THEN 'P1_22_13(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_CLT_OCT,0)))))) > 4
              THEN 'P1_22_19(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_PLAFOND,0)))))) > 4
              THEN 'P1_22_23(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_PLANCHER,0)))))) > 4
              THEN 'P1_22_24(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.PRD_REV_TAUX_NBR), 0),0)))))) > 3
              THEN 'P1_22_26(3,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_CLT_PRD_EN_CRS,0)))))) > 4
              THEN 'P1_22_27(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_MRG_ADD,0)))))) > 4
              THEN 'P1_22_28(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TAUX_MRG_MULT,0)))))) > 4
              THEN 'P1_22_29(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_PREM_DBLQ_FONDS is null then NULL else C_ENR.MNT_PREM_DBLQ_FONDS end,0)))))) > 16
              THEN 'P1_22_32(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(CASE WHEN C_ENR.CAP_THEO_REST <0 THEN 0 ELSE C_ENR.CAP_THEO_REST END,0)))))) > 16
              THEN 'P1_22_34(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_ACQUISITION), 0),0)))))) > 16
              THEN 'P1_22_44(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_ECH_EN_COURS,0)))))) > 16
              THEN 'P1_22_60(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL(CEIL((C_ENR.DT_FIN_ENG - C_ENR.DT_DEBUT_ENG) / 30), 0),0)))))) > 5
              THEN 'P1_31_17(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL(CEIL((C_ENR.DT_FIN_ENG - C_ENR.DT_DEBUT_ENG) / 30), 0),0)))))) > 5
              THEN 'P1_31_18(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(case when C_ENR.MNT_MRTR is not null then C_ENR.MNT_MRTR else NULL end,0)))))) > 19
              THEN 'P1_21_30(21,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.ETV_RATIO,0)))))) > 15
              THEN 'P1_21_43(24,9) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_DSCR,0)))))) > 4
              THEN 'P1_21_81(9,5) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_DSCR_PREC,0)))))) > 4
              THEN 'P1_21_82(9,5) ' END
           AS colunas_que_estouram
    FROM ENG_CORP_P1 C_ENR
   WHERE A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = 'TOTAL' OR 'TOTAL' = 'TOTAL')
      AND SUBSTR(C_ENR.CD_TYPE_RISQUE,1,4) IN ('TRE2','TRE4','TRE5')
UNION ALL
  SELECT 6 AS ins,
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_ACQUISITION), 0),0)))))) > 16
              THEN 'P1_3_50(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL(C_ENR.MNT_MTM, 0),0)))))) > 16
              THEN 'P1_3_52(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL(C_ENR.MNT_COUT_AMORTI, 0),0)))))) > 16
              THEN 'P1_3_54(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_NOMINAL), 0),0)))))) > 16
              THEN 'P1_3_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(ABS(TRUNC(C_ENR.MATURITE_EFF)),0)))))) > 2
              THEN 'P1_3_20(6,4) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_CONTRAT_ORIGINE,0)))))) > 16
              THEN 'P1_22_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.NB_TITRES,0)))))) > 10
              THEN 'P1_24_6(12,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 5
              THEN 'P1_31_17(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 5
              THEN 'P1_31_18(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.TX_HIST_POND_PARTICIPATION,0)))))) > 15
              THEN 'P1_21_60(24,9) ' END
           AS colunas_que_estouram
    FROM ENG_CORP_P1 C_ENR
   WHERE A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = 'TOTAL' OR 'TOTAL' = 'TOTAL')
      AND C_ENR.CD_TYPE_RISQUE IN ('EQU101')
UNION ALL
  SELECT 7 AS ins,
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_LOYER,0)))))) > 16
              THEN 'P1_4_14(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_NOMINAL), 0),0)))))) > 16
              THEN 'P1_4_16(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_INT_RD), 0),0)))))) > 16
              THEN 'P1_4_6(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(ABS(TRUNC(NVL(C_ENR.MATURITE_EFF, 0))),0)))))) > 2
              THEN 'P1_3_20(6,4) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_CONTRAT_ORIGINE,0)))))) > 16
              THEN 'P1_22_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 5
              THEN 'P1_31_17(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 5
              THEN 'P1_31_18(5,0) ' END
           AS colunas_que_estouram
    FROM ENG_CORP_P1 C_ENR
   WHERE A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = 'TOTAL' OR 'TOTAL' = 'TOTAL')
      AND C_ENR.CD_TYPE_RISQUE IN ('SIG201','INR101')
UNION ALL
  SELECT 8 AS ins,
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(C_ENR.MNT_LOYER,0)))))) > 16
              THEN 'P1_4_14(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_NOMINAL), 0),0)))))) > 16
              THEN 'P1_3_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MNT_MTM), 0),0)))))) > 16
              THEN 'P1_3_80(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MT_ASSIETE_INTERNE), 0),0)))))) > 16
              THEN 'P1_3_84(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MT_ASSIETE_REGLEMENTAIRE), 0),0)))))) > 16
              THEN 'P1_3_72(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(ABS(TRUNC(NVL(C_ENR.MATURITE_EFF, 0))),0)))))) > 2
              THEN 'P1_3_20(6,4) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(NVL((C_ENR.MT_CVA_COMPTA), 0),0)))))) > 16
              THEN 'P1_3_86(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(ABS(TRUNC(NVL(C_ENR.MT_SPREAD, 0))),0)))))) > 16
              THEN 'P1_3_10(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(97,0)))))) > 16
              THEN 'P1_22_8(18,2) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 5
              THEN 'P1_31_17(5,0) ' END ||
         CASE WHEN MAX(LENGTH(TO_CHAR(TRUNC(ABS(NVL(0,0)))))) > 5
              THEN 'P1_31_18(5,0) ' END
           AS colunas_que_estouram
    FROM ENG_CORP_P1 C_ENR
   WHERE A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = 'TOTAL' OR 'TOTAL' = 'TOTAL')
      AND C_ENR.CD_TYPE_RISQUE LIKE '%VAR1%'
 ORDER BY 1;
