-- =====================================================================
-- SIRL-1224 : alimentation de la table ENG_CORP_P1_BIS
-- Package  : pack_alim_tab_envoi_crrv4
-- Procedure: P_ALIM_ENG_CORP_P1_BIS
--
-- But : sortir les regles de gestion du pave P1 hors du spool
--       030_spool_Extract_CRRCORP.sql et les porter dans cette procedure,
--       qui remplit ENG_CORP_P1_BIS a partir de ENG_CORP_P1.
--       Le spool vPACT ne fera plus qu'un SELECT unique sur la table.
--
-- Le pave P1 est aujourd'hui produit par 8 SELECT sur ENG_CORP_P1 C_ENR,
-- qui partitionnent la population (perimetre NAT02 vs Hors-NAT, arriere de
-- paiement, montant, type de risque). Chaque SELECT devient ici un INSERT
-- qui garde SON filtre (clause WHERE) a l'identique.
--
--   #  ligne spool  FLAG_HN  filtre principal
--   1     590         N       risque std,  (CRD-VR)>=1 ou VR>=1
--   2    1089         N       arriere='Y', SOLD_K_A>=1, pas TRE2%
--   3    1592         N       arriere='Y', (CRD-VR)>=1 ou VR>=1, pas TRE2%
--   4    2894         O       CD_TYPE_RISQUE = 'TRE100'
--   5    3462         O       CD_TYPE_RISQUE LIKE 'TRE2/TRE4/TRE5'
--   6    4026         O       CD_TYPE_RISQUE = 'EQU101'
--   7    4606         O       CD_TYPE_RISQUE IN ('SIG201','INR101')
--   8    5061         O       CD_TYPE_RISQUE LIKE '%VAR1%'
--
-- ---------------------------------------------------------------------
-- REGLES DE CONVERSION  format spool  ->  valeur typee dans la table
-- ---------------------------------------------------------------------
--   RPAD(NVL(C_ENR.X,' '),n)              ->  C_ENR.X              (VARCHAR)
--   RPAD(C_ENR.X,n)                       ->  C_ENR.X
--   RPAD(' ',n)  (champ vide dans le spool)->  NULL   (colonne non listee)
--   to_char(C_ENR.DT,'YYYYMMDD')          ->  C_ENR.DT             (DATE, brute)
--   RPAD(NVL(TO_CHAR(C_ENR.DT,'YYYYMMDD'),' '),8) -> C_ENR.DT
--   'M' / 'P1' / 'Y' ... (litteral)       ->  litteral conserve
--   pack_utilitaire.F_FORMAT_TAUX(C_ENR.X)         -> C_ENR.X       (NUMBER)
--   pack_utilitaire.f_format_montant_bis2(<expr>)  -> <expr>        (NUMBER)
--   CASE ... THEN '+' ELSE '-' END (signe)-> supprime (le signe est porte
--                                            par le NUMBER)
--   NVL/CASE metier (ex defaut 'STD', '99990630', EAD<0 -> 0)
--                                         ->  CONSERVE (c'est une regle
--                                            de gestion, pas du formatage)
--
-- FLAG_HN -> CD_PERIMETRE :  'N' => 'NAT02'   ,  'O' => 'HORS_NAT02'
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) A AJOUTER DANS LA SPEC DU PACKAGE  pack_alim_tab_envoi_crrv4
-- ---------------------------------------------------------------------
--   PROCEDURE P_ALIM_ENG_CORP_P1_BIS (p_entite IN VARCHAR2);


-- ---------------------------------------------------------------------
-- 2) CORPS DE LA PROCEDURE (a inserer dans le PACKAGE BODY)
-- ---------------------------------------------------------------------
PROCEDURE P_ALIM_ENG_CORP_P1_BIS (p_entite IN VARCHAR2)
IS
BEGIN
    ------------------------------------------------------------------
    -- Etape 1 : vider la table avant de la remplir (SFG SIRL-1224)
    ------------------------------------------------------------------
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ENG_CORP_P1_BIS';

    ------------------------------------------------------------------
    -- INSERT #1  (standard NAT02 - spool L590)
    ------------------------------------------------------------------
    INSERT INTO ENG_CORP_P1_BIS
    (
        CD_PERIMETRE,
        P1_H_0_1,
        P1_H_0_2,
        P1_H_0_3,
        P1_H_0_4,
        P1_H_0_6,
        P1_H_1_1,
        P1_H_1_4,
        P1_H_1_6,
        P1_H_1_11,
        P1_1_1,
        P1_1_2,
        P1_4_34,
        P1_2_0,
        P1_2_4,
        P1_2_6,
        P1_2_18,
        P1_2_29,
        P1_3_2,
        P1_3_4,
        P1_18_1,
        P1_18_10,
        P1_18_5,
        P1_18_17,
        P1_18_18,
        P1_21_2,
        P1_2_99,
        P1_4_31,
        P1_4_8,
        P1_21_3,
        P1_22_56,
        P1_22_5,
        P1_22_7,
        P1_22_8,
        P1_22_9,
        P1_22_23,
        P1_22_37,
        P1_22_38,
        P1_22_44,
        P1_22_45,
        P1_22_60,
        P1_22_63,
        P1_23_1,
        P1_23_8,
        P1_31_17,
        P1_31_18,
        P1_29_4,
        P1_21_22,
        P1_21_23,
        P1_21_25,
        P1_21_26,
        P1_21_27,
        P1_21_28,
        P1_21_44,
        P1_21_45,
        P1_21_46,
        P1_21_38,
        P1_21_39,
        P1_21_40,
        P1_21_66,
        P1_21_68,
        P1_21_55,
        P1_8_13,
        P1_21_71,
        P1_21_72,
        P1_21_73,
        P1_21_74,
        P1_21_75,
        P1_21_76,
        P1_21_77,
        P1_21_78,
        P1_21_80,
        P1_21_86,
        P1_21_87,
        P1_21_88
        -- >>> A COMPLETER : champs CASE / non annotes (voir mapa_P1_select1.md)
    )
    SELECT
        'NAT02'                                                AS CD_PERIMETRE,
        C_ENR.DT_ARRETE                                        AS P1_H_0_1,
        C_ENR.CD_CONSO_CPT                                     AS P1_H_0_2,
        NVL(C_ENR.APPLI_SOURCE,'C_BTR')                        AS P1_H_0_3,
        'M'                                                    AS P1_H_0_4,
        'P1'                                                   AS P1_H_0_6,
        C_ENR.ID_TIERS_CALC                                    AS P1_H_1_1,
        C_ENR.ID_AUTORISATION                                  AS P1_H_1_4,
        C_ENR.ID_LIGNE_DET                                     AS P1_H_1_6,
        C_ENR.ID_ENGAGEMENT || '_C'                            AS P1_H_1_11,
        NVL(C_ENR.CD_METHODO_BALE2,'STD')                      AS P1_1_1,
        NVL(C_ENR.CODE_TRAIT_MOTEUR,'01')                      AS P1_1_2,
        'Y'                                                    AS P1_4_34,
        C_ENR.CD_TYPE_RISQUE                                   AS P1_2_0,
        NVL(C_ENR.CD_PORTEFEUILLE_BOOKING,'B')                 AS P1_2_4,
        C_ENR.CD_LIGNE_METIER                                  AS P1_2_6,
        C_ENR.CD_PORTEFEUILLE_BALE2                            AS P1_2_18,
        NVL(C_ENR.CD_NATURE_OPE,'NA020')                       AS P1_2_29,
        C_ENR.DT_DEBUT_ENG                                     AS P1_3_2,
        NVL(C_ENR.DT_FIN_ENG, TO_DATE('99990630','YYYYMMDD'))  AS P1_3_4,
        C_ENR.TX_LGD_PREDICTIF_LOCAL                           AS P1_18_1,
        C_ENR.TX_TRC                                           AS P1_18_10,
        CASE WHEN NVL(C_ENR.MNT_EAD_TOT,0) < 0 THEN 0 ELSE NVL(C_ENR.MNT_EAD_TOT,0) END AS P1_18_5,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_17,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_18,
        C_ENR.DT_RESTRUCTURATION                               AS P1_21_2,
        C_ENR.CD_METH_IFRS9_PD_ORIG                            AS P1_2_99,
        C_ENR.IND_PROD_SS_JACENT                               AS P1_4_31,
        NVL(C_ENR.TOP_ENG,'B')                                 AS P1_4_8,
        C_ENR.EVENMT_CRDT                                      AS P1_21_3,
        C_ENR.IND_PROD_ECH                                     AS P1_22_56,
        NVL(C_enr.NOTE_FIN_RET_ORI,'ND')                       AS P1_22_5,
        NVL(C_ENR.OBJ_FINANCIE,'97')                           AS P1_22_7,
        C_ENR.MNT_CONTRAT_ORIGINE                              AS P1_22_8,
        NVL(C_ENR.DEV_MNT_CONTRAT_ORIGINE,'EUR')               AS P1_22_9,
        C_ENR.TAUX_PLAFOND                                     AS P1_22_23,
        C_ENR.dt_exigte_prem_impy                              AS P1_22_37,
        C_ENR.DT_PASSAGE_DOUTEUX_COMPROMIS                     AS P1_22_38,
        nvl((C_ENR.MNT_ACQUISITION),0)                         AS P1_22_44,
        'EUR'                                                  AS P1_22_45,
        C_ENR.MNT_ECH_EN_COURS                                 AS P1_22_60,
        C_ENR.DATE_DEB_ENG_RENVL                               AS P1_22_63,
        C_ENR.ELI_OUT_MUT_PROV                                 AS P1_23_1,
        C_ENR.CD_METH_IFRS9_PD                                 AS P1_23_8,
        '+'                                                    AS P1_31_17,
        '+'                                                    AS P1_31_18,
        'EUR'                                                  AS P1_29_4,
        C_ENR.MOTIF_MRTR                                       AS P1_21_22,
        C_ENR.DT_DEBUT_MRTR                                    AS P1_21_23,
        C_ENR.STATUT_MRTR                                      AS P1_21_25,
        C_ENR.IND_MRTR_LEGISLATIF                              AS P1_21_26,
        C_ENR.IND_MRTR_CONTRACTUEL                             AS P1_21_27,
        C_ENR.CHAMP_APPL_MRTR                                  AS P1_21_28,
        C_ENR.IND_EXPO_QUAL_ELEVEE                             AS P1_21_44,
        C_ENR.IND_PHASE_OPE_PROJ_FIN                           AS P1_21_45,
        C_ENR.IND_CONF_CRIT_OPE                                AS P1_21_46,
        C_ENR.IND_IPRE                                         AS P1_21_38,
        C_ENR.IND_EXPO_ADC                                     AS P1_21_39,
        C_ENR.IND_REAL_COND_PONDERATION_PREFE                  AS P1_21_40,
        C_ENR.IND_UCC                                          AS P1_21_66,
        C_ENR.NIV_RISQUE_CRR3                                  AS P1_21_68,
        C_ENR.CD_NAT_OPE_ENG_CALC_FLOOR                        AS P1_21_55,
        C_ENR.USAGE_BIEN_FINANCE                               AS P1_8_13,
        C_ENR.COMMUNE                                          AS P1_21_71,
        C_ENR.NUM_VOIE                                         AS P1_21_72,
        C_ENR.EXTENSION                                        AS P1_21_73,
        C_ENR.TYPE_VOIE                                        AS P1_21_74,
        C_ENR.LIB_VOIE                                         AS P1_21_75,
        C_ENR.LIEU_DIT                                         AS P1_21_76,
        C_ENR.LATITUDE                                         AS P1_21_77,
        C_ENR.LONGITUDE                                        AS P1_21_78,
        C_ENR.CLASS_CPT_ELEMENT_COUV_DERIVE                    AS P1_21_80,
        C_ENR.CD_TYPE_BIEN_COMM                                AS P1_21_86,
        C_ENR.CD_EMPLACE_BIEN_COMM                             AS P1_21_87,
        C_ENR.IND_OPE_AVEC_RECOURS                             AS P1_21_88
        -- >>> A COMPLETER ...
    FROM ENG_CORP_P1 C_ENR
    WHERE
      A_EXTRAIRE = 'O'
      AND (C_ENR.CD_CONSO_CPT = p_entite OR p_entite = 'TOTAL')
      AND NVL(C_ENR.CD_ARR_PAIEMENT,'N') = 'N'
      AND NVL(C_ENR.FLAG_HN,'N')         = 'N'
      AND ( NVL(C_ENR.MNT_CRD,0) - NVL(C_ENR.MNT_VR,0) >= 1
            OR NVL(C_ENR.MNT_VR,0) >= 1 )
      AND C_ENR.CD_TYPE_RISQUE NOT IN ('TRE100','SIG201','EQU101','VAR104');

    ------------------------------------------------------------------
    -- INSERT #2  (NAT02 arriere='Y' solde - spool L1089)
    ------------------------------------------------------------------
    INSERT INTO ENG_CORP_P1_BIS
    (
        CD_PERIMETRE,
        P1_H_0_1,
        P1_H_0_2,
        P1_H_0_3,
        P1_H_0_4,
        P1_H_0_6,
        P1_H_1_1,
        P1_H_1_4,
        P1_H_1_6,
        P1_H_1_11,
        P1_1_1,
        P1_1_2,
        P1_4_34,
        P1_2_0,
        P1_2_4,
        P1_2_6,
        P1_2_18,
        P1_2_29,
        P1_3_2,
        P1_3_4,
        P1_18_1,
        P1_18_10,
        P1_18_5,
        P1_18_17,
        P1_18_18,
        P1_21_2,
        P1_2_99,
        P1_4_31,
        P1_4_8,
        P1_21_3,
        P1_22_56,
        P1_22_5,
        P1_22_7,
        P1_22_8,
        P1_22_9,
        P1_22_23,
        P1_22_37,
        P1_22_38,
        P1_22_44,
        P1_22_45,
        P1_22_60,
        P1_22_63,
        P1_23_1,
        P1_23_8,
        P1_31_17,
        P1_31_18,
        P1_29_4,
        P1_21_22,
        P1_21_23,
        P1_21_25,
        P1_21_26,
        P1_21_27,
        P1_21_28,
        P1_21_44,
        P1_21_45,
        P1_21_46,
        P1_21_38,
        P1_21_39,
        P1_21_40,
        P1_21_66,
        P1_21_68,
        P1_21_55,
        P1_8_13,
        P1_21_71,
        P1_21_72,
        P1_21_73,
        P1_21_74,
        P1_21_75,
        P1_21_76,
        P1_21_77,
        P1_21_78,
        P1_21_80,
        P1_21_86,
        P1_21_87,
        P1_21_88
        -- >>> A COMPLETER : champs CASE / non annotes (voir mapa_P1_select1.md)
    )
    SELECT
        'NAT02'                                                AS CD_PERIMETRE,
        C_ENR.DT_ARRETE                                        AS P1_H_0_1,
        C_ENR.CD_CONSO_CPT                                     AS P1_H_0_2,
        NVL(C_ENR.APPLI_SOURCE,'C_BTR')                        AS P1_H_0_3,
        'M'                                                    AS P1_H_0_4,
        'P1'                                                   AS P1_H_0_6,
        C_ENR.ID_TIERS_CALC                                    AS P1_H_1_1,
        C_ENR.ID_AUTORISATION                                  AS P1_H_1_4,
        C_ENR.ID_LIGNE_DET                                     AS P1_H_1_6,
        C_ENR.ID_ENGAGEMENT || '_C'                            AS P1_H_1_11,
        NVL(C_ENR.CD_METHODO_BALE2,'STD')                      AS P1_1_1,
        NVL(C_ENR.CODE_TRAIT_MOTEUR,'01')                      AS P1_1_2,
        'Y'                                                    AS P1_4_34,
        C_ENR.CD_TYPE_RISQUE                                   AS P1_2_0,
        NVL(C_ENR.CD_PORTEFEUILLE_BOOKING,'B')                 AS P1_2_4,
        C_ENR.CD_LIGNE_METIER                                  AS P1_2_6,
        C_ENR.CD_PORTEFEUILLE_BALE2                            AS P1_2_18,
        NVL(C_ENR.CD_NATURE_OPE,'NA020')                       AS P1_2_29,
        C_ENR.DT_DEBUT_ENG                                     AS P1_3_2,
        NVL(C_ENR.DT_FIN_ENG, TO_DATE('99990630','YYYYMMDD'))  AS P1_3_4,
        C_ENR.TX_LGD_PREDICTIF_LOCAL                           AS P1_18_1,
        C_ENR.TX_TRC                                           AS P1_18_10,
        CASE WHEN NVL(C_ENR.MNT_EAD_TOT,0) < 0 THEN 0 ELSE NVL(C_ENR.MNT_EAD_TOT,0) END AS P1_18_5,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_17,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_18,
        C_ENR.DT_RESTRUCTURATION                               AS P1_21_2,
        C_ENR.CD_METH_IFRS9_PD_ORIG                            AS P1_2_99,
        C_ENR.IND_PROD_SS_JACENT                               AS P1_4_31,
        NVL(C_ENR.TOP_ENG,'B')                                 AS P1_4_8,
        C_ENR.EVENMT_CRDT                                      AS P1_21_3,
        C_ENR.IND_PROD_ECH                                     AS P1_22_56,
        NVL(C_enr.NOTE_FIN_RET_ORI,'ND')                       AS P1_22_5,
        NVL(C_ENR.OBJ_FINANCIE,'97')                           AS P1_22_7,
        C_ENR.MNT_CONTRAT_ORIGINE                              AS P1_22_8,
        NVL(C_ENR.DEV_MNT_CONTRAT_ORIGINE,'EUR')               AS P1_22_9,
        C_ENR.TAUX_PLAFOND                                     AS P1_22_23,
        C_ENR.dt_exigte_prem_impy                              AS P1_22_37,
        C_ENR.DT_PASSAGE_DOUTEUX_COMPROMIS                     AS P1_22_38,
        nvl((C_ENR.MNT_ACQUISITION),0)                         AS P1_22_44,
        'EUR'                                                  AS P1_22_45,
        C_ENR.MNT_ECH_EN_COURS                                 AS P1_22_60,
        C_ENR.DATE_DEB_ENG_RENVL                               AS P1_22_63,
        C_ENR.ELI_OUT_MUT_PROV                                 AS P1_23_1,
        C_ENR.CD_METH_IFRS9_PD                                 AS P1_23_8,
        '+'                                                    AS P1_31_17,
        '+'                                                    AS P1_31_18,
        'EUR'                                                  AS P1_29_4,
        C_ENR.MOTIF_MRTR                                       AS P1_21_22,
        C_ENR.DT_DEBUT_MRTR                                    AS P1_21_23,
        C_ENR.STATUT_MRTR                                      AS P1_21_25,
        C_ENR.IND_MRTR_LEGISLATIF                              AS P1_21_26,
        C_ENR.IND_MRTR_CONTRACTUEL                             AS P1_21_27,
        C_ENR.CHAMP_APPL_MRTR                                  AS P1_21_28,
        C_ENR.IND_EXPO_QUAL_ELEVEE                             AS P1_21_44,
        C_ENR.IND_PHASE_OPE_PROJ_FIN                           AS P1_21_45,
        C_ENR.IND_CONF_CRIT_OPE                                AS P1_21_46,
        C_ENR.IND_IPRE                                         AS P1_21_38,
        C_ENR.IND_EXPO_ADC                                     AS P1_21_39,
        C_ENR.IND_REAL_COND_PONDERATION_PREFE                  AS P1_21_40,
        C_ENR.IND_UCC                                          AS P1_21_66,
        C_ENR.NIV_RISQUE_CRR3                                  AS P1_21_68,
        C_ENR.CD_NAT_OPE_ENG_CALC_FLOOR                        AS P1_21_55,
        C_ENR.USAGE_BIEN_FINANCE                               AS P1_8_13,
        C_ENR.COMMUNE                                          AS P1_21_71,
        C_ENR.NUM_VOIE                                         AS P1_21_72,
        C_ENR.EXTENSION                                        AS P1_21_73,
        C_ENR.TYPE_VOIE                                        AS P1_21_74,
        C_ENR.LIB_VOIE                                         AS P1_21_75,
        C_ENR.LIEU_DIT                                         AS P1_21_76,
        C_ENR.LATITUDE                                         AS P1_21_77,
        C_ENR.LONGITUDE                                        AS P1_21_78,
        C_ENR.CLASS_CPT_ELEMENT_COUV_DERIVE                    AS P1_21_80,
        C_ENR.CD_TYPE_BIEN_COMM                                AS P1_21_86,
        C_ENR.CD_EMPLACE_BIEN_COMM                             AS P1_21_87,
        C_ENR.IND_OPE_AVEC_RECOURS                             AS P1_21_88
        -- >>> A COMPLETER ...
    FROM ENG_CORP_P1 C_ENR
    WHERE
      A_EXTRAIRE = 'O'
      AND (C_ENR.CD_CONSO_CPT = p_entite OR p_entite = 'TOTAL')
      AND NVL(C_ENR.CD_ARR_PAIEMENT,'N') = 'Y'
      AND NVL(C_ENR.FLAG_HN,'N')         = 'N'
      AND NVL(C_ENR.MNT_SOLD_K_A,0) >= 1
      AND C_ENR.CD_TYPE_RISQUE NOT IN ('TRE100','SIG201','EQU101','VAR104')
      AND ( C_ENR.CD_TYPE_RISQUE NOT LIKE 'TRE2%' );

    ------------------------------------------------------------------
    -- INSERT #3  (NAT02 arriere='Y' CRD/VR - spool L1592)
    ------------------------------------------------------------------
    INSERT INTO ENG_CORP_P1_BIS
    (
        CD_PERIMETRE,
        P1_H_0_1,
        P1_H_0_2,
        P1_H_0_3,
        P1_H_0_4,
        P1_H_0_6,
        P1_H_1_1,
        P1_H_1_4,
        P1_H_1_6,
        P1_H_1_11,
        P1_1_1,
        P1_1_2,
        P1_4_34,
        P1_2_0,
        P1_2_4,
        P1_2_6,
        P1_2_18,
        P1_2_29,
        P1_3_2,
        P1_3_4,
        P1_18_1,
        P1_18_10,
        P1_18_5,
        P1_18_17,
        P1_18_18,
        P1_21_2,
        P1_2_99,
        P1_4_31,
        P1_4_8,
        P1_21_3,
        P1_22_56,
        P1_22_5,
        P1_22_7,
        P1_22_8,
        P1_22_9,
        P1_22_23,
        P1_22_37,
        P1_22_38,
        P1_22_44,
        P1_22_45,
        P1_22_60,
        P1_22_63,
        P1_23_1,
        P1_23_8,
        P1_31_17,
        P1_31_18,
        P1_29_4,
        P1_21_22,
        P1_21_23,
        P1_21_25,
        P1_21_26,
        P1_21_27,
        P1_21_28,
        P1_21_44,
        P1_21_45,
        P1_21_46,
        P1_21_38,
        P1_21_39,
        P1_21_40,
        P1_21_66,
        P1_21_68,
        P1_21_55,
        P1_8_13,
        P1_21_71,
        P1_21_72,
        P1_21_73,
        P1_21_74,
        P1_21_75,
        P1_21_76,
        P1_21_77,
        P1_21_78,
        P1_21_80,
        P1_21_86,
        P1_21_87,
        P1_21_88
        -- >>> A COMPLETER : champs CASE / non annotes (voir mapa_P1_select1.md)
    )
    SELECT
        'NAT02'                                                AS CD_PERIMETRE,
        C_ENR.DT_ARRETE                                        AS P1_H_0_1,
        C_ENR.CD_CONSO_CPT                                     AS P1_H_0_2,
        NVL(C_ENR.APPLI_SOURCE,'C_BTR')                        AS P1_H_0_3,
        'M'                                                    AS P1_H_0_4,
        'P1'                                                   AS P1_H_0_6,
        C_ENR.ID_TIERS_CALC                                    AS P1_H_1_1,
        C_ENR.ID_AUTORISATION                                  AS P1_H_1_4,
        C_ENR.ID_LIGNE_DET                                     AS P1_H_1_6,
        C_ENR.ID_ENGAGEMENT || '_C'                            AS P1_H_1_11,
        NVL(C_ENR.CD_METHODO_BALE2,'STD')                      AS P1_1_1,
        NVL(C_ENR.CODE_TRAIT_MOTEUR,'01')                      AS P1_1_2,
        'Y'                                                    AS P1_4_34,
        C_ENR.CD_TYPE_RISQUE                                   AS P1_2_0,
        NVL(C_ENR.CD_PORTEFEUILLE_BOOKING,'B')                 AS P1_2_4,
        C_ENR.CD_LIGNE_METIER                                  AS P1_2_6,
        C_ENR.CD_PORTEFEUILLE_BALE2                            AS P1_2_18,
        NVL(C_ENR.CD_NATURE_OPE,'NA020')                       AS P1_2_29,
        C_ENR.DT_DEBUT_ENG                                     AS P1_3_2,
        NVL(C_ENR.DT_FIN_ENG, TO_DATE('99990630','YYYYMMDD'))  AS P1_3_4,
        C_ENR.TX_LGD_PREDICTIF_LOCAL                           AS P1_18_1,
        C_ENR.TX_TRC                                           AS P1_18_10,
        CASE WHEN NVL(C_ENR.MNT_EAD_TOT,0) < 0 THEN 0 ELSE NVL(C_ENR.MNT_EAD_TOT,0) END AS P1_18_5,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_17,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_18,
        C_ENR.DT_RESTRUCTURATION                               AS P1_21_2,
        C_ENR.CD_METH_IFRS9_PD_ORIG                            AS P1_2_99,
        C_ENR.IND_PROD_SS_JACENT                               AS P1_4_31,
        NVL(C_ENR.TOP_ENG,'B')                                 AS P1_4_8,
        C_ENR.EVENMT_CRDT                                      AS P1_21_3,
        C_ENR.IND_PROD_ECH                                     AS P1_22_56,
        NVL(C_enr.NOTE_FIN_RET_ORI,'ND')                       AS P1_22_5,
        NVL(C_ENR.OBJ_FINANCIE,'97')                           AS P1_22_7,
        C_ENR.MNT_CONTRAT_ORIGINE                              AS P1_22_8,
        NVL(C_ENR.DEV_MNT_CONTRAT_ORIGINE,'EUR')               AS P1_22_9,
        C_ENR.TAUX_PLAFOND                                     AS P1_22_23,
        C_ENR.dt_exigte_prem_impy                              AS P1_22_37,
        C_ENR.DT_PASSAGE_DOUTEUX_COMPROMIS                     AS P1_22_38,
        nvl((C_ENR.MNT_ACQUISITION),0)                         AS P1_22_44,
        'EUR'                                                  AS P1_22_45,
        C_ENR.MNT_ECH_EN_COURS                                 AS P1_22_60,
        C_ENR.DATE_DEB_ENG_RENVL                               AS P1_22_63,
        C_ENR.ELI_OUT_MUT_PROV                                 AS P1_23_1,
        C_ENR.CD_METH_IFRS9_PD                                 AS P1_23_8,
        '+'                                                    AS P1_31_17,
        '+'                                                    AS P1_31_18,
        'EUR'                                                  AS P1_29_4,
        C_ENR.MOTIF_MRTR                                       AS P1_21_22,
        C_ENR.DT_DEBUT_MRTR                                    AS P1_21_23,
        C_ENR.STATUT_MRTR                                      AS P1_21_25,
        C_ENR.IND_MRTR_LEGISLATIF                              AS P1_21_26,
        C_ENR.IND_MRTR_CONTRACTUEL                             AS P1_21_27,
        C_ENR.CHAMP_APPL_MRTR                                  AS P1_21_28,
        C_ENR.IND_EXPO_QUAL_ELEVEE                             AS P1_21_44,
        C_ENR.IND_PHASE_OPE_PROJ_FIN                           AS P1_21_45,
        C_ENR.IND_CONF_CRIT_OPE                                AS P1_21_46,
        C_ENR.IND_IPRE                                         AS P1_21_38,
        C_ENR.IND_EXPO_ADC                                     AS P1_21_39,
        C_ENR.IND_REAL_COND_PONDERATION_PREFE                  AS P1_21_40,
        C_ENR.IND_UCC                                          AS P1_21_66,
        C_ENR.NIV_RISQUE_CRR3                                  AS P1_21_68,
        C_ENR.CD_NAT_OPE_ENG_CALC_FLOOR                        AS P1_21_55,
        C_ENR.USAGE_BIEN_FINANCE                               AS P1_8_13,
        C_ENR.COMMUNE                                          AS P1_21_71,
        C_ENR.NUM_VOIE                                         AS P1_21_72,
        C_ENR.EXTENSION                                        AS P1_21_73,
        C_ENR.TYPE_VOIE                                        AS P1_21_74,
        C_ENR.LIB_VOIE                                         AS P1_21_75,
        C_ENR.LIEU_DIT                                         AS P1_21_76,
        C_ENR.LATITUDE                                         AS P1_21_77,
        C_ENR.LONGITUDE                                        AS P1_21_78,
        C_ENR.CLASS_CPT_ELEMENT_COUV_DERIVE                    AS P1_21_80,
        C_ENR.CD_TYPE_BIEN_COMM                                AS P1_21_86,
        C_ENR.CD_EMPLACE_BIEN_COMM                             AS P1_21_87,
        C_ENR.IND_OPE_AVEC_RECOURS                             AS P1_21_88
        -- >>> A COMPLETER ...
    FROM ENG_CORP_P1 C_ENR
    WHERE
      A_EXTRAIRE = 'O'
      AND (C_ENR.CD_CONSO_CPT = p_entite OR p_entite = 'TOTAL')
      AND NVL(C_ENR.CD_ARR_PAIEMENT,'N') = 'Y'
      AND NVL(C_ENR.FLAG_HN,'N')         = 'N'
      AND C_ENR.CD_TYPE_RISQUE NOT IN ('TRE100','SIG201','EQU101','VAR104')
      AND ( C_ENR.CD_TYPE_RISQUE NOT LIKE 'TRE2%' )
      AND ( NVL(C_ENR.MNT_CRD,0) - NVL(C_ENR.MNT_VR,0) >= 1
            OR NVL(C_ENR.MNT_VR,0) >= 1 );

    ------------------------------------------------------------------
    -- INSERT #4  (Hors-NAT TRE100 - spool L2894)
    ------------------------------------------------------------------
    INSERT INTO ENG_CORP_P1_BIS
    (
        CD_PERIMETRE,
        P1_H_0_1,
        P1_H_0_2,
        P1_H_0_3,
        P1_H_0_4,
        P1_H_0_6,
        P1_H_1_1,
        P1_H_1_4,
        P1_H_1_6,
        P1_H_1_11,
        P1_1_1,
        P1_1_2,
        P1_4_34,
        P1_2_0,
        P1_2_4,
        P1_2_6,
        P1_2_18,
        P1_2_29,
        P1_3_2,
        P1_3_4,
        P1_18_1,
        P1_18_10,
        P1_18_5,
        P1_18_17,
        P1_18_18,
        P1_21_2,
        P1_2_99,
        P1_4_31,
        P1_4_8,
        P1_21_3,
        P1_22_56,
        P1_22_5,
        P1_22_7,
        P1_22_8,
        P1_22_9,
        P1_22_23,
        P1_22_37,
        P1_22_38,
        P1_22_44,
        P1_22_45,
        P1_22_60,
        P1_22_63,
        P1_23_1,
        P1_23_8,
        P1_31_17,
        P1_31_18,
        P1_29_4,
        P1_21_22,
        P1_21_23,
        P1_21_25,
        P1_21_26,
        P1_21_27,
        P1_21_28,
        P1_21_44,
        P1_21_45,
        P1_21_46,
        P1_21_38,
        P1_21_39,
        P1_21_40,
        P1_21_66,
        P1_21_68,
        P1_21_55,
        P1_8_13,
        P1_21_71,
        P1_21_72,
        P1_21_73,
        P1_21_74,
        P1_21_75,
        P1_21_76,
        P1_21_77,
        P1_21_78,
        P1_21_80,
        P1_21_86,
        P1_21_87,
        P1_21_88
        -- >>> A COMPLETER : champs CASE / non annotes (voir mapa_P1_select1.md)
    )
    SELECT
        'HORS_NAT02'                                           AS CD_PERIMETRE,
        C_ENR.DT_ARRETE                                        AS P1_H_0_1,
        C_ENR.CD_CONSO_CPT                                     AS P1_H_0_2,
        NVL(C_ENR.APPLI_SOURCE,'C_BTR')                        AS P1_H_0_3,
        'M'                                                    AS P1_H_0_4,
        'P1'                                                   AS P1_H_0_6,
        C_ENR.ID_TIERS_CALC                                    AS P1_H_1_1,
        C_ENR.ID_AUTORISATION                                  AS P1_H_1_4,
        C_ENR.ID_LIGNE_DET                                     AS P1_H_1_6,
        C_ENR.ID_ENGAGEMENT || '_C'                            AS P1_H_1_11,
        NVL(C_ENR.CD_METHODO_BALE2,'STD')                      AS P1_1_1,
        NVL(C_ENR.CODE_TRAIT_MOTEUR,'01')                      AS P1_1_2,
        'Y'                                                    AS P1_4_34,
        C_ENR.CD_TYPE_RISQUE                                   AS P1_2_0,
        NVL(C_ENR.CD_PORTEFEUILLE_BOOKING,'B')                 AS P1_2_4,
        C_ENR.CD_LIGNE_METIER                                  AS P1_2_6,
        C_ENR.CD_PORTEFEUILLE_BALE2                            AS P1_2_18,
        NVL(C_ENR.CD_NATURE_OPE,'NA020')                       AS P1_2_29,
        C_ENR.DT_DEBUT_ENG                                     AS P1_3_2,
        NVL(C_ENR.DT_FIN_ENG, TO_DATE('99990630','YYYYMMDD'))  AS P1_3_4,
        C_ENR.TX_LGD_PREDICTIF_LOCAL                           AS P1_18_1,
        C_ENR.TX_TRC                                           AS P1_18_10,
        CASE WHEN NVL(C_ENR.MNT_EAD_TOT,0) < 0 THEN 0 ELSE NVL(C_ENR.MNT_EAD_TOT,0) END AS P1_18_5,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_17,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_18,
        C_ENR.DT_RESTRUCTURATION                               AS P1_21_2,
        C_ENR.CD_METH_IFRS9_PD_ORIG                            AS P1_2_99,
        C_ENR.IND_PROD_SS_JACENT                               AS P1_4_31,
        NVL(C_ENR.TOP_ENG,'B')                                 AS P1_4_8,
        C_ENR.EVENMT_CRDT                                      AS P1_21_3,
        C_ENR.IND_PROD_ECH                                     AS P1_22_56,
        NVL(C_enr.NOTE_FIN_RET_ORI,'ND')                       AS P1_22_5,
        NVL(C_ENR.OBJ_FINANCIE,'97')                           AS P1_22_7,
        C_ENR.MNT_CONTRAT_ORIGINE                              AS P1_22_8,
        NVL(C_ENR.DEV_MNT_CONTRAT_ORIGINE,'EUR')               AS P1_22_9,
        C_ENR.TAUX_PLAFOND                                     AS P1_22_23,
        C_ENR.dt_exigte_prem_impy                              AS P1_22_37,
        C_ENR.DT_PASSAGE_DOUTEUX_COMPROMIS                     AS P1_22_38,
        nvl((C_ENR.MNT_ACQUISITION),0)                         AS P1_22_44,
        'EUR'                                                  AS P1_22_45,
        C_ENR.MNT_ECH_EN_COURS                                 AS P1_22_60,
        C_ENR.DATE_DEB_ENG_RENVL                               AS P1_22_63,
        C_ENR.ELI_OUT_MUT_PROV                                 AS P1_23_1,
        C_ENR.CD_METH_IFRS9_PD                                 AS P1_23_8,
        '+'                                                    AS P1_31_17,
        '+'                                                    AS P1_31_18,
        'EUR'                                                  AS P1_29_4,
        C_ENR.MOTIF_MRTR                                       AS P1_21_22,
        C_ENR.DT_DEBUT_MRTR                                    AS P1_21_23,
        C_ENR.STATUT_MRTR                                      AS P1_21_25,
        C_ENR.IND_MRTR_LEGISLATIF                              AS P1_21_26,
        C_ENR.IND_MRTR_CONTRACTUEL                             AS P1_21_27,
        C_ENR.CHAMP_APPL_MRTR                                  AS P1_21_28,
        C_ENR.IND_EXPO_QUAL_ELEVEE                             AS P1_21_44,
        C_ENR.IND_PHASE_OPE_PROJ_FIN                           AS P1_21_45,
        C_ENR.IND_CONF_CRIT_OPE                                AS P1_21_46,
        C_ENR.IND_IPRE                                         AS P1_21_38,
        C_ENR.IND_EXPO_ADC                                     AS P1_21_39,
        C_ENR.IND_REAL_COND_PONDERATION_PREFE                  AS P1_21_40,
        C_ENR.IND_UCC                                          AS P1_21_66,
        C_ENR.NIV_RISQUE_CRR3                                  AS P1_21_68,
        C_ENR.CD_NAT_OPE_ENG_CALC_FLOOR                        AS P1_21_55,
        C_ENR.USAGE_BIEN_FINANCE                               AS P1_8_13,
        C_ENR.COMMUNE                                          AS P1_21_71,
        C_ENR.NUM_VOIE                                         AS P1_21_72,
        C_ENR.EXTENSION                                        AS P1_21_73,
        C_ENR.TYPE_VOIE                                        AS P1_21_74,
        C_ENR.LIB_VOIE                                         AS P1_21_75,
        C_ENR.LIEU_DIT                                         AS P1_21_76,
        C_ENR.LATITUDE                                         AS P1_21_77,
        C_ENR.LONGITUDE                                        AS P1_21_78,
        C_ENR.CLASS_CPT_ELEMENT_COUV_DERIVE                    AS P1_21_80,
        C_ENR.CD_TYPE_BIEN_COMM                                AS P1_21_86,
        C_ENR.CD_EMPLACE_BIEN_COMM                             AS P1_21_87,
        C_ENR.IND_OPE_AVEC_RECOURS                             AS P1_21_88
        -- >>> A COMPLETER ...
    FROM ENG_CORP_P1 C_ENR
    WHERE
      A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = p_entite OR p_entite = 'TOTAL')
      AND C_ENR.CD_TYPE_RISQUE IN ('TRE100');

    ------------------------------------------------------------------
    -- INSERT #5  (Hors-NAT TRE2/4/5 - spool L3462)
    ------------------------------------------------------------------
    INSERT INTO ENG_CORP_P1_BIS
    (
        CD_PERIMETRE,
        P1_H_0_1,
        P1_H_0_2,
        P1_H_0_3,
        P1_H_0_4,
        P1_H_0_6,
        P1_H_1_1,
        P1_H_1_4,
        P1_H_1_6,
        P1_H_1_11,
        P1_1_1,
        P1_1_2,
        P1_4_34,
        P1_2_0,
        P1_2_4,
        P1_2_6,
        P1_2_18,
        P1_2_29,
        P1_3_2,
        P1_3_4,
        P1_18_1,
        P1_18_10,
        P1_18_5,
        P1_18_17,
        P1_18_18,
        P1_21_2,
        P1_2_99,
        P1_4_31,
        P1_4_8,
        P1_21_3,
        P1_22_56,
        P1_22_5,
        P1_22_7,
        P1_22_8,
        P1_22_9,
        P1_22_23,
        P1_22_37,
        P1_22_38,
        P1_22_44,
        P1_22_45,
        P1_22_60,
        P1_22_63,
        P1_23_1,
        P1_23_8,
        P1_31_17,
        P1_31_18,
        P1_29_4,
        P1_21_22,
        P1_21_23,
        P1_21_25,
        P1_21_26,
        P1_21_27,
        P1_21_28,
        P1_21_44,
        P1_21_45,
        P1_21_46,
        P1_21_38,
        P1_21_39,
        P1_21_40,
        P1_21_66,
        P1_21_68,
        P1_21_55,
        P1_8_13,
        P1_21_71,
        P1_21_72,
        P1_21_73,
        P1_21_74,
        P1_21_75,
        P1_21_76,
        P1_21_77,
        P1_21_78,
        P1_21_80,
        P1_21_86,
        P1_21_87,
        P1_21_88
        -- >>> A COMPLETER : champs CASE / non annotes (voir mapa_P1_select1.md)
    )
    SELECT
        'HORS_NAT02'                                           AS CD_PERIMETRE,
        C_ENR.DT_ARRETE                                        AS P1_H_0_1,
        C_ENR.CD_CONSO_CPT                                     AS P1_H_0_2,
        NVL(C_ENR.APPLI_SOURCE,'C_BTR')                        AS P1_H_0_3,
        'M'                                                    AS P1_H_0_4,
        'P1'                                                   AS P1_H_0_6,
        C_ENR.ID_TIERS_CALC                                    AS P1_H_1_1,
        C_ENR.ID_AUTORISATION                                  AS P1_H_1_4,
        C_ENR.ID_LIGNE_DET                                     AS P1_H_1_6,
        C_ENR.ID_ENGAGEMENT || '_C'                            AS P1_H_1_11,
        NVL(C_ENR.CD_METHODO_BALE2,'STD')                      AS P1_1_1,
        NVL(C_ENR.CODE_TRAIT_MOTEUR,'01')                      AS P1_1_2,
        'Y'                                                    AS P1_4_34,
        C_ENR.CD_TYPE_RISQUE                                   AS P1_2_0,
        NVL(C_ENR.CD_PORTEFEUILLE_BOOKING,'B')                 AS P1_2_4,
        C_ENR.CD_LIGNE_METIER                                  AS P1_2_6,
        C_ENR.CD_PORTEFEUILLE_BALE2                            AS P1_2_18,
        NVL(C_ENR.CD_NATURE_OPE,'NA020')                       AS P1_2_29,
        C_ENR.DT_DEBUT_ENG                                     AS P1_3_2,
        NVL(C_ENR.DT_FIN_ENG, TO_DATE('99990630','YYYYMMDD'))  AS P1_3_4,
        C_ENR.TX_LGD_PREDICTIF_LOCAL                           AS P1_18_1,
        C_ENR.TX_TRC                                           AS P1_18_10,
        CASE WHEN NVL(C_ENR.MNT_EAD_TOT,0) < 0 THEN 0 ELSE NVL(C_ENR.MNT_EAD_TOT,0) END AS P1_18_5,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_17,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_18,
        C_ENR.DT_RESTRUCTURATION                               AS P1_21_2,
        C_ENR.CD_METH_IFRS9_PD_ORIG                            AS P1_2_99,
        C_ENR.IND_PROD_SS_JACENT                               AS P1_4_31,
        NVL(C_ENR.TOP_ENG,'B')                                 AS P1_4_8,
        C_ENR.EVENMT_CRDT                                      AS P1_21_3,
        C_ENR.IND_PROD_ECH                                     AS P1_22_56,
        NVL(C_enr.NOTE_FIN_RET_ORI,'ND')                       AS P1_22_5,
        NVL(C_ENR.OBJ_FINANCIE,'97')                           AS P1_22_7,
        C_ENR.MNT_CONTRAT_ORIGINE                              AS P1_22_8,
        NVL(C_ENR.DEV_MNT_CONTRAT_ORIGINE,'EUR')               AS P1_22_9,
        C_ENR.TAUX_PLAFOND                                     AS P1_22_23,
        C_ENR.dt_exigte_prem_impy                              AS P1_22_37,
        C_ENR.DT_PASSAGE_DOUTEUX_COMPROMIS                     AS P1_22_38,
        nvl((C_ENR.MNT_ACQUISITION),0)                         AS P1_22_44,
        'EUR'                                                  AS P1_22_45,
        C_ENR.MNT_ECH_EN_COURS                                 AS P1_22_60,
        C_ENR.DATE_DEB_ENG_RENVL                               AS P1_22_63,
        C_ENR.ELI_OUT_MUT_PROV                                 AS P1_23_1,
        C_ENR.CD_METH_IFRS9_PD                                 AS P1_23_8,
        '+'                                                    AS P1_31_17,
        '+'                                                    AS P1_31_18,
        'EUR'                                                  AS P1_29_4,
        C_ENR.MOTIF_MRTR                                       AS P1_21_22,
        C_ENR.DT_DEBUT_MRTR                                    AS P1_21_23,
        C_ENR.STATUT_MRTR                                      AS P1_21_25,
        C_ENR.IND_MRTR_LEGISLATIF                              AS P1_21_26,
        C_ENR.IND_MRTR_CONTRACTUEL                             AS P1_21_27,
        C_ENR.CHAMP_APPL_MRTR                                  AS P1_21_28,
        C_ENR.IND_EXPO_QUAL_ELEVEE                             AS P1_21_44,
        C_ENR.IND_PHASE_OPE_PROJ_FIN                           AS P1_21_45,
        C_ENR.IND_CONF_CRIT_OPE                                AS P1_21_46,
        C_ENR.IND_IPRE                                         AS P1_21_38,
        C_ENR.IND_EXPO_ADC                                     AS P1_21_39,
        C_ENR.IND_REAL_COND_PONDERATION_PREFE                  AS P1_21_40,
        C_ENR.IND_UCC                                          AS P1_21_66,
        C_ENR.NIV_RISQUE_CRR3                                  AS P1_21_68,
        C_ENR.CD_NAT_OPE_ENG_CALC_FLOOR                        AS P1_21_55,
        C_ENR.USAGE_BIEN_FINANCE                               AS P1_8_13,
        C_ENR.COMMUNE                                          AS P1_21_71,
        C_ENR.NUM_VOIE                                         AS P1_21_72,
        C_ENR.EXTENSION                                        AS P1_21_73,
        C_ENR.TYPE_VOIE                                        AS P1_21_74,
        C_ENR.LIB_VOIE                                         AS P1_21_75,
        C_ENR.LIEU_DIT                                         AS P1_21_76,
        C_ENR.LATITUDE                                         AS P1_21_77,
        C_ENR.LONGITUDE                                        AS P1_21_78,
        C_ENR.CLASS_CPT_ELEMENT_COUV_DERIVE                    AS P1_21_80,
        C_ENR.CD_TYPE_BIEN_COMM                                AS P1_21_86,
        C_ENR.CD_EMPLACE_BIEN_COMM                             AS P1_21_87,
        C_ENR.IND_OPE_AVEC_RECOURS                             AS P1_21_88
        -- >>> A COMPLETER ...
    FROM ENG_CORP_P1 C_ENR
    WHERE
      A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = p_entite OR p_entite = 'TOTAL')
      AND SUBSTR(C_ENR.CD_TYPE_RISQUE,1,4) IN ('TRE2','TRE4','TRE5');

    ------------------------------------------------------------------
    -- INSERT #6  (Hors-NAT EQU101 - spool L4026)
    ------------------------------------------------------------------
    INSERT INTO ENG_CORP_P1_BIS
    (
        CD_PERIMETRE,
        P1_H_0_1,
        P1_H_0_2,
        P1_H_0_3,
        P1_H_0_4,
        P1_H_0_6,
        P1_H_1_1,
        P1_H_1_4,
        P1_H_1_6,
        P1_H_1_11,
        P1_1_1,
        P1_1_2,
        P1_4_34,
        P1_2_0,
        P1_2_4,
        P1_2_6,
        P1_2_18,
        P1_2_29,
        P1_3_2,
        P1_3_4,
        P1_18_1,
        P1_18_10,
        P1_18_5,
        P1_18_17,
        P1_18_18,
        P1_21_2,
        P1_2_99,
        P1_4_31,
        P1_4_8,
        P1_21_3,
        P1_22_56,
        P1_22_5,
        P1_22_7,
        P1_22_8,
        P1_22_9,
        P1_22_23,
        P1_22_37,
        P1_22_38,
        P1_22_44,
        P1_22_45,
        P1_22_60,
        P1_22_63,
        P1_23_1,
        P1_23_8,
        P1_31_17,
        P1_31_18,
        P1_29_4,
        P1_21_22,
        P1_21_23,
        P1_21_25,
        P1_21_26,
        P1_21_27,
        P1_21_28,
        P1_21_44,
        P1_21_45,
        P1_21_46,
        P1_21_38,
        P1_21_39,
        P1_21_40,
        P1_21_66,
        P1_21_68,
        P1_21_55,
        P1_8_13,
        P1_21_71,
        P1_21_72,
        P1_21_73,
        P1_21_74,
        P1_21_75,
        P1_21_76,
        P1_21_77,
        P1_21_78,
        P1_21_80,
        P1_21_86,
        P1_21_87,
        P1_21_88
        -- >>> A COMPLETER : champs CASE / non annotes (voir mapa_P1_select1.md)
    )
    SELECT
        'HORS_NAT02'                                           AS CD_PERIMETRE,
        C_ENR.DT_ARRETE                                        AS P1_H_0_1,
        C_ENR.CD_CONSO_CPT                                     AS P1_H_0_2,
        NVL(C_ENR.APPLI_SOURCE,'C_BTR')                        AS P1_H_0_3,
        'M'                                                    AS P1_H_0_4,
        'P1'                                                   AS P1_H_0_6,
        C_ENR.ID_TIERS_CALC                                    AS P1_H_1_1,
        C_ENR.ID_AUTORISATION                                  AS P1_H_1_4,
        C_ENR.ID_LIGNE_DET                                     AS P1_H_1_6,
        C_ENR.ID_ENGAGEMENT || '_C'                            AS P1_H_1_11,
        NVL(C_ENR.CD_METHODO_BALE2,'STD')                      AS P1_1_1,
        NVL(C_ENR.CODE_TRAIT_MOTEUR,'01')                      AS P1_1_2,
        'Y'                                                    AS P1_4_34,
        C_ENR.CD_TYPE_RISQUE                                   AS P1_2_0,
        NVL(C_ENR.CD_PORTEFEUILLE_BOOKING,'B')                 AS P1_2_4,
        C_ENR.CD_LIGNE_METIER                                  AS P1_2_6,
        C_ENR.CD_PORTEFEUILLE_BALE2                            AS P1_2_18,
        NVL(C_ENR.CD_NATURE_OPE,'NA020')                       AS P1_2_29,
        C_ENR.DT_DEBUT_ENG                                     AS P1_3_2,
        NVL(C_ENR.DT_FIN_ENG, TO_DATE('99990630','YYYYMMDD'))  AS P1_3_4,
        C_ENR.TX_LGD_PREDICTIF_LOCAL                           AS P1_18_1,
        C_ENR.TX_TRC                                           AS P1_18_10,
        CASE WHEN NVL(C_ENR.MNT_EAD_TOT,0) < 0 THEN 0 ELSE NVL(C_ENR.MNT_EAD_TOT,0) END AS P1_18_5,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_17,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_18,
        C_ENR.DT_RESTRUCTURATION                               AS P1_21_2,
        C_ENR.CD_METH_IFRS9_PD_ORIG                            AS P1_2_99,
        C_ENR.IND_PROD_SS_JACENT                               AS P1_4_31,
        NVL(C_ENR.TOP_ENG,'B')                                 AS P1_4_8,
        C_ENR.EVENMT_CRDT                                      AS P1_21_3,
        C_ENR.IND_PROD_ECH                                     AS P1_22_56,
        NVL(C_enr.NOTE_FIN_RET_ORI,'ND')                       AS P1_22_5,
        NVL(C_ENR.OBJ_FINANCIE,'97')                           AS P1_22_7,
        C_ENR.MNT_CONTRAT_ORIGINE                              AS P1_22_8,
        NVL(C_ENR.DEV_MNT_CONTRAT_ORIGINE,'EUR')               AS P1_22_9,
        C_ENR.TAUX_PLAFOND                                     AS P1_22_23,
        C_ENR.dt_exigte_prem_impy                              AS P1_22_37,
        C_ENR.DT_PASSAGE_DOUTEUX_COMPROMIS                     AS P1_22_38,
        nvl((C_ENR.MNT_ACQUISITION),0)                         AS P1_22_44,
        'EUR'                                                  AS P1_22_45,
        C_ENR.MNT_ECH_EN_COURS                                 AS P1_22_60,
        C_ENR.DATE_DEB_ENG_RENVL                               AS P1_22_63,
        C_ENR.ELI_OUT_MUT_PROV                                 AS P1_23_1,
        C_ENR.CD_METH_IFRS9_PD                                 AS P1_23_8,
        '+'                                                    AS P1_31_17,
        '+'                                                    AS P1_31_18,
        'EUR'                                                  AS P1_29_4,
        C_ENR.MOTIF_MRTR                                       AS P1_21_22,
        C_ENR.DT_DEBUT_MRTR                                    AS P1_21_23,
        C_ENR.STATUT_MRTR                                      AS P1_21_25,
        C_ENR.IND_MRTR_LEGISLATIF                              AS P1_21_26,
        C_ENR.IND_MRTR_CONTRACTUEL                             AS P1_21_27,
        C_ENR.CHAMP_APPL_MRTR                                  AS P1_21_28,
        C_ENR.IND_EXPO_QUAL_ELEVEE                             AS P1_21_44,
        C_ENR.IND_PHASE_OPE_PROJ_FIN                           AS P1_21_45,
        C_ENR.IND_CONF_CRIT_OPE                                AS P1_21_46,
        C_ENR.IND_IPRE                                         AS P1_21_38,
        C_ENR.IND_EXPO_ADC                                     AS P1_21_39,
        C_ENR.IND_REAL_COND_PONDERATION_PREFE                  AS P1_21_40,
        C_ENR.IND_UCC                                          AS P1_21_66,
        C_ENR.NIV_RISQUE_CRR3                                  AS P1_21_68,
        C_ENR.CD_NAT_OPE_ENG_CALC_FLOOR                        AS P1_21_55,
        C_ENR.USAGE_BIEN_FINANCE                               AS P1_8_13,
        C_ENR.COMMUNE                                          AS P1_21_71,
        C_ENR.NUM_VOIE                                         AS P1_21_72,
        C_ENR.EXTENSION                                        AS P1_21_73,
        C_ENR.TYPE_VOIE                                        AS P1_21_74,
        C_ENR.LIB_VOIE                                         AS P1_21_75,
        C_ENR.LIEU_DIT                                         AS P1_21_76,
        C_ENR.LATITUDE                                         AS P1_21_77,
        C_ENR.LONGITUDE                                        AS P1_21_78,
        C_ENR.CLASS_CPT_ELEMENT_COUV_DERIVE                    AS P1_21_80,
        C_ENR.CD_TYPE_BIEN_COMM                                AS P1_21_86,
        C_ENR.CD_EMPLACE_BIEN_COMM                             AS P1_21_87,
        C_ENR.IND_OPE_AVEC_RECOURS                             AS P1_21_88
        -- >>> A COMPLETER ...
    FROM ENG_CORP_P1 C_ENR
    WHERE
      A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = p_entite OR p_entite = 'TOTAL')
      AND C_ENR.CD_TYPE_RISQUE IN ('EQU101');

    ------------------------------------------------------------------
    -- INSERT #7  (Hors-NAT SIG201/INR101 - spool L4606)
    ------------------------------------------------------------------
    INSERT INTO ENG_CORP_P1_BIS
    (
        CD_PERIMETRE,
        P1_H_0_1,
        P1_H_0_2,
        P1_H_0_3,
        P1_H_0_4,
        P1_H_0_6,
        P1_H_1_1,
        P1_H_1_4,
        P1_H_1_6,
        P1_H_1_11,
        P1_1_1,
        P1_1_2,
        P1_4_34,
        P1_2_0,
        P1_2_4,
        P1_2_6,
        P1_2_18,
        P1_2_29,
        P1_3_2,
        P1_3_4,
        P1_18_1,
        P1_18_10,
        P1_18_5,
        P1_18_17,
        P1_18_18,
        P1_21_2,
        P1_2_99,
        P1_4_31,
        P1_4_8,
        P1_21_3,
        P1_22_56,
        P1_22_5,
        P1_22_7,
        P1_22_8,
        P1_22_9,
        P1_22_23,
        P1_22_37,
        P1_22_38,
        P1_22_44,
        P1_22_45,
        P1_22_60,
        P1_22_63,
        P1_23_1,
        P1_23_8,
        P1_31_17,
        P1_31_18,
        P1_29_4,
        P1_21_22,
        P1_21_23,
        P1_21_25,
        P1_21_26,
        P1_21_27,
        P1_21_28,
        P1_21_44,
        P1_21_45,
        P1_21_46,
        P1_21_38,
        P1_21_39,
        P1_21_40,
        P1_21_66,
        P1_21_68,
        P1_21_55,
        P1_8_13,
        P1_21_71,
        P1_21_72,
        P1_21_73,
        P1_21_74,
        P1_21_75,
        P1_21_76,
        P1_21_77,
        P1_21_78,
        P1_21_80,
        P1_21_86,
        P1_21_87,
        P1_21_88
        -- >>> A COMPLETER : champs CASE / non annotes (voir mapa_P1_select1.md)
    )
    SELECT
        'HORS_NAT02'                                           AS CD_PERIMETRE,
        C_ENR.DT_ARRETE                                        AS P1_H_0_1,
        C_ENR.CD_CONSO_CPT                                     AS P1_H_0_2,
        NVL(C_ENR.APPLI_SOURCE,'C_BTR')                        AS P1_H_0_3,
        'M'                                                    AS P1_H_0_4,
        'P1'                                                   AS P1_H_0_6,
        C_ENR.ID_TIERS_CALC                                    AS P1_H_1_1,
        C_ENR.ID_AUTORISATION                                  AS P1_H_1_4,
        C_ENR.ID_LIGNE_DET                                     AS P1_H_1_6,
        C_ENR.ID_ENGAGEMENT || '_C'                            AS P1_H_1_11,
        NVL(C_ENR.CD_METHODO_BALE2,'STD')                      AS P1_1_1,
        NVL(C_ENR.CODE_TRAIT_MOTEUR,'01')                      AS P1_1_2,
        'Y'                                                    AS P1_4_34,
        C_ENR.CD_TYPE_RISQUE                                   AS P1_2_0,
        NVL(C_ENR.CD_PORTEFEUILLE_BOOKING,'B')                 AS P1_2_4,
        C_ENR.CD_LIGNE_METIER                                  AS P1_2_6,
        C_ENR.CD_PORTEFEUILLE_BALE2                            AS P1_2_18,
        NVL(C_ENR.CD_NATURE_OPE,'NA020')                       AS P1_2_29,
        C_ENR.DT_DEBUT_ENG                                     AS P1_3_2,
        NVL(C_ENR.DT_FIN_ENG, TO_DATE('99990630','YYYYMMDD'))  AS P1_3_4,
        C_ENR.TX_LGD_PREDICTIF_LOCAL                           AS P1_18_1,
        C_ENR.TX_TRC                                           AS P1_18_10,
        CASE WHEN NVL(C_ENR.MNT_EAD_TOT,0) < 0 THEN 0 ELSE NVL(C_ENR.MNT_EAD_TOT,0) END AS P1_18_5,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_17,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_18,
        C_ENR.DT_RESTRUCTURATION                               AS P1_21_2,
        C_ENR.CD_METH_IFRS9_PD_ORIG                            AS P1_2_99,
        C_ENR.IND_PROD_SS_JACENT                               AS P1_4_31,
        NVL(C_ENR.TOP_ENG,'B')                                 AS P1_4_8,
        C_ENR.EVENMT_CRDT                                      AS P1_21_3,
        C_ENR.IND_PROD_ECH                                     AS P1_22_56,
        NVL(C_enr.NOTE_FIN_RET_ORI,'ND')                       AS P1_22_5,
        NVL(C_ENR.OBJ_FINANCIE,'97')                           AS P1_22_7,
        C_ENR.MNT_CONTRAT_ORIGINE                              AS P1_22_8,
        NVL(C_ENR.DEV_MNT_CONTRAT_ORIGINE,'EUR')               AS P1_22_9,
        C_ENR.TAUX_PLAFOND                                     AS P1_22_23,
        C_ENR.dt_exigte_prem_impy                              AS P1_22_37,
        C_ENR.DT_PASSAGE_DOUTEUX_COMPROMIS                     AS P1_22_38,
        nvl((C_ENR.MNT_ACQUISITION),0)                         AS P1_22_44,
        'EUR'                                                  AS P1_22_45,
        C_ENR.MNT_ECH_EN_COURS                                 AS P1_22_60,
        C_ENR.DATE_DEB_ENG_RENVL                               AS P1_22_63,
        C_ENR.ELI_OUT_MUT_PROV                                 AS P1_23_1,
        C_ENR.CD_METH_IFRS9_PD                                 AS P1_23_8,
        '+'                                                    AS P1_31_17,
        '+'                                                    AS P1_31_18,
        'EUR'                                                  AS P1_29_4,
        C_ENR.MOTIF_MRTR                                       AS P1_21_22,
        C_ENR.DT_DEBUT_MRTR                                    AS P1_21_23,
        C_ENR.STATUT_MRTR                                      AS P1_21_25,
        C_ENR.IND_MRTR_LEGISLATIF                              AS P1_21_26,
        C_ENR.IND_MRTR_CONTRACTUEL                             AS P1_21_27,
        C_ENR.CHAMP_APPL_MRTR                                  AS P1_21_28,
        C_ENR.IND_EXPO_QUAL_ELEVEE                             AS P1_21_44,
        C_ENR.IND_PHASE_OPE_PROJ_FIN                           AS P1_21_45,
        C_ENR.IND_CONF_CRIT_OPE                                AS P1_21_46,
        C_ENR.IND_IPRE                                         AS P1_21_38,
        C_ENR.IND_EXPO_ADC                                     AS P1_21_39,
        C_ENR.IND_REAL_COND_PONDERATION_PREFE                  AS P1_21_40,
        C_ENR.IND_UCC                                          AS P1_21_66,
        C_ENR.NIV_RISQUE_CRR3                                  AS P1_21_68,
        C_ENR.CD_NAT_OPE_ENG_CALC_FLOOR                        AS P1_21_55,
        C_ENR.USAGE_BIEN_FINANCE                               AS P1_8_13,
        C_ENR.COMMUNE                                          AS P1_21_71,
        C_ENR.NUM_VOIE                                         AS P1_21_72,
        C_ENR.EXTENSION                                        AS P1_21_73,
        C_ENR.TYPE_VOIE                                        AS P1_21_74,
        C_ENR.LIB_VOIE                                         AS P1_21_75,
        C_ENR.LIEU_DIT                                         AS P1_21_76,
        C_ENR.LATITUDE                                         AS P1_21_77,
        C_ENR.LONGITUDE                                        AS P1_21_78,
        C_ENR.CLASS_CPT_ELEMENT_COUV_DERIVE                    AS P1_21_80,
        C_ENR.CD_TYPE_BIEN_COMM                                AS P1_21_86,
        C_ENR.CD_EMPLACE_BIEN_COMM                             AS P1_21_87,
        C_ENR.IND_OPE_AVEC_RECOURS                             AS P1_21_88
        -- >>> A COMPLETER ...
    FROM ENG_CORP_P1 C_ENR
    WHERE
      A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = p_entite OR p_entite = 'TOTAL')
      AND C_ENR.CD_TYPE_RISQUE IN ('SIG201','INR101');

    ------------------------------------------------------------------
    -- INSERT #8  (Hors-NAT VAR1 - spool L5061)
    ------------------------------------------------------------------
    INSERT INTO ENG_CORP_P1_BIS
    (
        CD_PERIMETRE,
        P1_H_0_1,
        P1_H_0_2,
        P1_H_0_3,
        P1_H_0_4,
        P1_H_0_6,
        P1_H_1_1,
        P1_H_1_4,
        P1_H_1_6,
        P1_H_1_11,
        P1_1_1,
        P1_1_2,
        P1_4_34,
        P1_2_0,
        P1_2_4,
        P1_2_6,
        P1_2_18,
        P1_2_29,
        P1_3_2,
        P1_3_4,
        P1_18_1,
        P1_18_10,
        P1_18_5,
        P1_18_17,
        P1_18_18,
        P1_21_2,
        P1_2_99,
        P1_4_31,
        P1_4_8,
        P1_21_3,
        P1_22_56,
        P1_22_5,
        P1_22_7,
        P1_22_8,
        P1_22_9,
        P1_22_23,
        P1_22_37,
        P1_22_38,
        P1_22_44,
        P1_22_45,
        P1_22_60,
        P1_22_63,
        P1_23_1,
        P1_23_8,
        P1_31_17,
        P1_31_18,
        P1_29_4,
        P1_21_22,
        P1_21_23,
        P1_21_25,
        P1_21_26,
        P1_21_27,
        P1_21_28,
        P1_21_44,
        P1_21_45,
        P1_21_46,
        P1_21_38,
        P1_21_39,
        P1_21_40,
        P1_21_66,
        P1_21_68,
        P1_21_55,
        P1_8_13,
        P1_21_71,
        P1_21_72,
        P1_21_73,
        P1_21_74,
        P1_21_75,
        P1_21_76,
        P1_21_77,
        P1_21_78,
        P1_21_80,
        P1_21_86,
        P1_21_87,
        P1_21_88
        -- >>> A COMPLETER : champs CASE / non annotes (voir mapa_P1_select1.md)
    )
    SELECT
        'HORS_NAT02'                                           AS CD_PERIMETRE,
        C_ENR.DT_ARRETE                                        AS P1_H_0_1,
        C_ENR.CD_CONSO_CPT                                     AS P1_H_0_2,
        NVL(C_ENR.APPLI_SOURCE,'C_BTR')                        AS P1_H_0_3,
        'M'                                                    AS P1_H_0_4,
        'P1'                                                   AS P1_H_0_6,
        C_ENR.ID_TIERS_CALC                                    AS P1_H_1_1,
        C_ENR.ID_AUTORISATION                                  AS P1_H_1_4,
        C_ENR.ID_LIGNE_DET                                     AS P1_H_1_6,
        C_ENR.ID_ENGAGEMENT || '_C'                            AS P1_H_1_11,
        NVL(C_ENR.CD_METHODO_BALE2,'STD')                      AS P1_1_1,
        NVL(C_ENR.CODE_TRAIT_MOTEUR,'01')                      AS P1_1_2,
        'Y'                                                    AS P1_4_34,
        C_ENR.CD_TYPE_RISQUE                                   AS P1_2_0,
        NVL(C_ENR.CD_PORTEFEUILLE_BOOKING,'B')                 AS P1_2_4,
        C_ENR.CD_LIGNE_METIER                                  AS P1_2_6,
        C_ENR.CD_PORTEFEUILLE_BALE2                            AS P1_2_18,
        NVL(C_ENR.CD_NATURE_OPE,'NA020')                       AS P1_2_29,
        C_ENR.DT_DEBUT_ENG                                     AS P1_3_2,
        NVL(C_ENR.DT_FIN_ENG, TO_DATE('99990630','YYYYMMDD'))  AS P1_3_4,
        C_ENR.TX_LGD_PREDICTIF_LOCAL                           AS P1_18_1,
        C_ENR.TX_TRC                                           AS P1_18_10,
        CASE WHEN NVL(C_ENR.MNT_EAD_TOT,0) < 0 THEN 0 ELSE NVL(C_ENR.MNT_EAD_TOT,0) END AS P1_18_5,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_17,
        C_ENR.CD_DEVISE_MNT_RISQ                               AS P1_18_18,
        C_ENR.DT_RESTRUCTURATION                               AS P1_21_2,
        C_ENR.CD_METH_IFRS9_PD_ORIG                            AS P1_2_99,
        C_ENR.IND_PROD_SS_JACENT                               AS P1_4_31,
        NVL(C_ENR.TOP_ENG,'B')                                 AS P1_4_8,
        C_ENR.EVENMT_CRDT                                      AS P1_21_3,
        C_ENR.IND_PROD_ECH                                     AS P1_22_56,
        NVL(C_enr.NOTE_FIN_RET_ORI,'ND')                       AS P1_22_5,
        NVL(C_ENR.OBJ_FINANCIE,'97')                           AS P1_22_7,
        C_ENR.MNT_CONTRAT_ORIGINE                              AS P1_22_8,
        NVL(C_ENR.DEV_MNT_CONTRAT_ORIGINE,'EUR')               AS P1_22_9,
        C_ENR.TAUX_PLAFOND                                     AS P1_22_23,
        C_ENR.dt_exigte_prem_impy                              AS P1_22_37,
        C_ENR.DT_PASSAGE_DOUTEUX_COMPROMIS                     AS P1_22_38,
        nvl((C_ENR.MNT_ACQUISITION),0)                         AS P1_22_44,
        'EUR'                                                  AS P1_22_45,
        C_ENR.MNT_ECH_EN_COURS                                 AS P1_22_60,
        C_ENR.DATE_DEB_ENG_RENVL                               AS P1_22_63,
        C_ENR.ELI_OUT_MUT_PROV                                 AS P1_23_1,
        C_ENR.CD_METH_IFRS9_PD                                 AS P1_23_8,
        '+'                                                    AS P1_31_17,
        '+'                                                    AS P1_31_18,
        'EUR'                                                  AS P1_29_4,
        C_ENR.MOTIF_MRTR                                       AS P1_21_22,
        C_ENR.DT_DEBUT_MRTR                                    AS P1_21_23,
        C_ENR.STATUT_MRTR                                      AS P1_21_25,
        C_ENR.IND_MRTR_LEGISLATIF                              AS P1_21_26,
        C_ENR.IND_MRTR_CONTRACTUEL                             AS P1_21_27,
        C_ENR.CHAMP_APPL_MRTR                                  AS P1_21_28,
        C_ENR.IND_EXPO_QUAL_ELEVEE                             AS P1_21_44,
        C_ENR.IND_PHASE_OPE_PROJ_FIN                           AS P1_21_45,
        C_ENR.IND_CONF_CRIT_OPE                                AS P1_21_46,
        C_ENR.IND_IPRE                                         AS P1_21_38,
        C_ENR.IND_EXPO_ADC                                     AS P1_21_39,
        C_ENR.IND_REAL_COND_PONDERATION_PREFE                  AS P1_21_40,
        C_ENR.IND_UCC                                          AS P1_21_66,
        C_ENR.NIV_RISQUE_CRR3                                  AS P1_21_68,
        C_ENR.CD_NAT_OPE_ENG_CALC_FLOOR                        AS P1_21_55,
        C_ENR.USAGE_BIEN_FINANCE                               AS P1_8_13,
        C_ENR.COMMUNE                                          AS P1_21_71,
        C_ENR.NUM_VOIE                                         AS P1_21_72,
        C_ENR.EXTENSION                                        AS P1_21_73,
        C_ENR.TYPE_VOIE                                        AS P1_21_74,
        C_ENR.LIB_VOIE                                         AS P1_21_75,
        C_ENR.LIEU_DIT                                         AS P1_21_76,
        C_ENR.LATITUDE                                         AS P1_21_77,
        C_ENR.LONGITUDE                                        AS P1_21_78,
        C_ENR.CLASS_CPT_ELEMENT_COUV_DERIVE                    AS P1_21_80,
        C_ENR.CD_TYPE_BIEN_COMM                                AS P1_21_86,
        C_ENR.CD_EMPLACE_BIEN_COMM                             AS P1_21_87,
        C_ENR.IND_OPE_AVEC_RECOURS                             AS P1_21_88
        -- >>> A COMPLETER ...
    FROM ENG_CORP_P1 C_ENR
    WHERE
      A_EXTRAIRE = 'O'
      AND C_ENR.FLAG_HN = 'O'
      AND (C_ENR.CD_CONSO_CPT = p_entite OR p_entite = 'TOTAL')
      AND C_ENR.CD_TYPE_RISQUE LIKE '%VAR1%';

    COMMIT;
END P_ALIM_ENG_CORP_P1_BIS;
